"""add openai_api_key to users

Revision ID: 38c3ed3600f5
Revises: 19d4f6d968ac
Create Date: 2025-04-24 21:19:04.104947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c3ed3600f5'
down_revision: Union[str, None] = '19d4f6d968ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openai_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'openai_api_key')
    # ### end Alembic commands ###
